sudo : require
language: cpp
# compiler: gcc
before_install:
- sudo pip install codecov

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

script:
  - make
  - ./get_code_cov
  - codecov

after_success:
- bash <(curl -s https://codecov.io/bash)