addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

# sudo : require
language: cpp
# compiler: gcc
# before_install:
# - sudo pip install codecov
script:
  - make
  # - ./get_code_cov.sh
  # - codecov

# after_success:
# - bash <(curl -s https://codecov.io/bash)